# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920bd1bb805f5dc33d4c5c2f0ce3ec249c26cd470c1d024dbcc4c0adb0784c1eb6c42dd0be8cff0e53f930d1d49523dcd1c87d79a5dac2abf75bbd05d93e9312

test:
  secret_key_base: 2e1c908543da40abd7b854978ea91d38adfa8c92954a15bd29eb871108b60cd8b422a9bf5648cf4367c18b20f9bf0cd314aa42fe685967aa6bff93c6313d298e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
